module.exports = [
  {
    id: "1",
    make: "Mercedes",
    model: "c3",
    color: "Black",
    year: "2020",
    VIN: "5YJBMWSI89DFP1471",
    Odometer: "5000 miles",
    image: "/images/mercedes_c3_black.jpg",
  },
  {
    id: "2",
    make: "BMW",
    model: "3 Series",
    color: "Blue",
    year: "2020",
    VIN: "5YJBMWSI89DFP1472",
    Odometer: "10,000 miles",
    image: "/images/bmw_blue.jpg",
  },
  {
    id: "3",
    make: "BMW",
    model: "i8",
    color: "White",
    year: "2019",
    VIN: "5YJBMWSI89DFP1473",
    Odometer: "20,000 miles",
    image: "/images/bmw_i8_white.jpg",
  },
  {
    id: "4",
    make: "Jaguar",
    model: "F-TYPE",
    color: "Red",
    year: "2021",
    VIN: "5YJBMWSI89DFP1474",
    Odometer: "3,500 miles",
    image: "/images/jaguar_f-type_red.jpg",
  },
];
